In [8]:
import torch
from torch.utils.data import DataLoader, random_split, Subset
from torch.nn import MSELoss, CrossEntropyLoss
from torchvision import transforms
import torch.optim as optim
import os
import time
from sklearn.model_selection import train_test_split

from data_loader import FaceDataset
from model import AgeGenderModel
torch.cuda.is_available()

True

In [3]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


In [4]:
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

In [5]:
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])  

full_dataset = FaceDataset(root_dir='dataset', transform=transform)

In [ ]:
# 2. Extract labels and indices for stratification (without loading images)
# We stratify on Gender (index 1 in the filename split)
indices = []
genders = []
print("Preparing stratified split...")
for i, img_name in enumerate(full_dataset.image_files):
    try:
        parts = img_name.split('_')
        gender = int(parts[1])
        indices.append(i)
        genders.append(gender)
    except (IndexError, ValueError):
        continue

Preparing stratified split...


In [9]:
# 3. Perform Stratified Splitting (80% Train, 10% Val, 10% Test)
# First split: Train vs Temp (20%)
train_idx, temp_idx, _, temp_genders = train_test_split(
    indices, genders, test_size=0.20, stratify=genders, random_state=42
)

# Second split: Split Temp into Val (50% of Temp) and Test (50% of Temp)
val_idx, test_idx = train_test_split(
    temp_idx, test_size=0.50, stratify=temp_genders, random_state=42
)

In [10]:
train_subset = Subset(full_dataset, train_idx)
val_subset = Subset(full_dataset, val_idx)
test_subset = Subset(full_dataset, test_idx)

print(f"Dataset Split: Train={len(train_subset)}, Val={len(val_subset)}, Test={len(test_subset)}")

Dataset Split: Train=7908, Val=989, Test=989


In [ ]:
train_loader = DataLoader(train_subset, batch_size=32, shuffle=True, num_workers=4)
val_loader = DataLoader(val_subset, batch_size=32, shuffle=False)

In [ ]:
# filtered_indices = [i for i, (data, label) in enumerate(full_dataset) if data is not None]
# dataset = torch.utils.data.Subset(full_dataset,BATCH_SIZE filtered_indices)

# train_size = int(0.8 * len(dataset))
# val_size = int(0.1 * len(dataset))
# test_size = len(dataset) - train_size - val_size
# train_dataset, val_dataset, test_dataset = random_split(dataset, [train_size, val_size, test_size])


In [ ]:
# train_loader = DataLoader(train_dataset, batch_size = 32, shuffle = True, num_workers = 4)
# val_loader = DataLoader(val_dataset, batch_size = 32, shuffle = False, num_workers = 4)
# test_loader = DataLoader(test_dataset, batch_size = 32, shuffle = False, num_workers = 4)

In [ ]:
# image_files = [f for f in os.listdir('dataset') if f.endswith(".jpg")]
# len(image_files)
# for i in image_files:
#     parts = i.split('_')
#     gender = int(parts[1])
#     if gender > 1:
#         print(gender, i)

In [ ]:
# next(iter(train_loader))[1].shape
# next(iter(train_loader))[1][:, 1]
# z = 1
# for i, (images, labels) in enumerate(train_loader) :
#     images = images.to(device)
#     ages = labels[:, 0].to(device)
#     genders = labels[:, 1].long().to(device)
#     print(genders)
#     z += 1
#     if z > 5: break

tensor([0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
        0, 0, 1, 0, 1, 1, 0, 1], device='cuda:0')
tensor([1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 0, 0, 1, 0, 0], device='cuda:0')
tensor([1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
        1, 0, 0, 0, 0, 0, 1, 0], device='cuda:0')
tensor([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 1], device='cuda:0')
tensor([1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
        1, 1, 0, 0, 0, 0, 1, 1], device='cuda:0')


In [13]:
model = AgeGenderModel()
print(next(model.parameters()).dtype)

torch.float32


In [14]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = AgeGenderModel().to(device)

age_criterion = MSELoss()
gender_criterion = CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = 0.001)

In [15]:
num_gender_classes = 2

num_epochs = 20
for epoch in range(num_epochs):
    start_time = time.time()
    model.train()
    running_loss = 0.0
    for i, (images, labels) in enumerate(train_loader) :
        images = images.to(device)
        ages = labels[:, 0].to(device)
        genders = labels[:, 1].long().to(device)
        #max_gender = genders.max().item()
        #if max_gender >= num_gender_classes:
        #    print(i, genders)
        #    print(f"Error in batch {i} Epoch {epoch+1}")
        #    print(f"Maximun gender value {max_gender}")
        #    break

        optimizer.zero_grad()

        age_pred, gender_pred = model(images)

        age_loss = age_criterion(age_pred.squeeze(), ages)
        gender_loss = gender_criterion(gender_pred, genders)
        total_loss = age_loss + gender_loss

        total_loss.backward()

        optimizer.step()

        running_loss += total_loss.item()
    end_time = time.time()
    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {running_loss/len(train_loader):4f}, Time: {end_time - start_time:.2f}sec")

torch.save(model.state_dict(),'models/model_stratified_splitting.pth')
print("Training complete. Model saved.")


Epoch 1/20, Loss: 309.708253, Time: 19.25sec
Epoch 2/20, Loss: 150.684900, Time: 18.85sec
Epoch 3/20, Loss: 119.497418, Time: 18.43sec
Epoch 4/20, Loss: 91.601643, Time: 18.45sec
Epoch 5/20, Loss: 79.221542, Time: 18.50sec
Epoch 6/20, Loss: 62.871583, Time: 18.77sec
Epoch 7/20, Loss: 63.240752, Time: 18.74sec
Epoch 8/20, Loss: 75.862692, Time: 18.55sec
Epoch 9/20, Loss: 43.816049, Time: 18.59sec
Epoch 10/20, Loss: 29.407671, Time: 18.44sec
Epoch 11/20, Loss: 30.775887, Time: 18.43sec
Epoch 12/20, Loss: 19.675680, Time: 18.48sec
Epoch 13/20, Loss: 17.481218, Time: 18.48sec
Epoch 14/20, Loss: 15.577893, Time: 18.32sec
Epoch 15/20, Loss: 15.375673, Time: 18.32sec
Epoch 16/20, Loss: 18.000527, Time: 18.50sec
Epoch 17/20, Loss: 13.164262, Time: 18.32sec
Epoch 18/20, Loss: 10.720619, Time: 18.49sec
Epoch 19/20, Loss: 9.878415, Time: 18.42sec
Epoch 20/20, Loss: 98.533719, Time: 18.29sec
Training complete. Model saved.
