In [1]:
import torch
from torch.utils.data import DataLoader, random_split, Subset
from torch.nn import MSELoss, CrossEntropyLoss
from torchvision import transforms
import torch.optim as optim
import os
import time
from sklearn.model_selection import train_test_split

from data_loader import FaceDataset
from model import AgeGenderModel
torch.cuda.is_available()

True

In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


In [3]:
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

In [6]:
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])  

full_dataset = FaceDataset(root_dir='augmented_dataset', transform=transform)

In [7]:
# 2. Extract labels and indices for stratification (without loading images)
# We stratify on Gender (index 1 in the filename split)
indices = []
genders = []
print("Preparing stratified split...")
for i, img_name in enumerate(full_dataset.image_files):
    try:
        parts = img_name.split('_')
        gender = int(parts[1])
        indices.append(i)
        genders.append(gender)
    except (IndexError, ValueError):
        continue

Preparing stratified split...


In [8]:
# 3. Perform Stratified Splitting (80% Train, 10% Val, 10% Test)
# First split: Train vs Temp (20%)
train_idx, temp_idx, _, temp_genders = train_test_split(
    indices, genders, test_size=0.20, stratify=genders, random_state=42
)

# Second split: Split Temp into Val (50% of Temp) and Test (50% of Temp)
val_idx, test_idx = train_test_split(
    temp_idx, test_size=0.50, stratify=temp_genders, random_state=42
)

In [9]:
train_subset = Subset(full_dataset, train_idx)
val_subset = Subset(full_dataset, val_idx)
test_subset = Subset(full_dataset, test_idx)

print(f"Dataset Split: Train={len(train_subset)}, Val={len(val_subset)}, Test={len(test_subset)}")

Dataset Split: Train=79416, Val=9927, Test=9927


In [10]:
train_loader = DataLoader(train_subset, batch_size=32, shuffle=True, num_workers=4)
val_loader = DataLoader(val_subset, batch_size=32, shuffle=False)

In [ ]:
# filtered_indices = [i for i, (data, label) in enumerate(full_dataset) if data is not None]
# dataset = torch.utils.data.Subset(full_dataset,BATCH_SIZE filtered_indices)

# train_size = int(0.8 * len(dataset))
# val_size = int(0.1 * len(dataset))
# test_size = len(dataset) - train_size - val_size
# train_dataset, val_dataset, test_dataset = random_split(dataset, [train_size, val_size, test_size])


In [ ]:
# train_loader = DataLoader(train_dataset, batch_size = 32, shuffle = True, num_workers = 4)
# val_loader = DataLoader(val_dataset, batch_size = 32, shuffle = False, num_workers = 4)
# test_loader = DataLoader(test_dataset, batch_size = 32, shuffle = False, num_workers = 4)

In [ ]:
# image_files = [f for f in os.listdir('dataset') if f.endswith(".jpg")]
# len(image_files)
# for i in image_files:
#     parts = i.split('_')
#     gender = int(parts[1])
#     if gender > 1:
#         print(gender, i)

In [ ]:
# next(iter(train_loader))[1].shape
# next(iter(train_loader))[1][:, 1]
# z = 1
# for i, (images, labels) in enumerate(train_loader) :
#     images = images.to(device)
#     ages = labels[:, 0].to(device)
#     genders = labels[:, 1].long().to(device)
#     print(genders)
#     z += 1
#     if z > 5: break

tensor([0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
        0, 0, 1, 0, 1, 1, 0, 1], device='cuda:0')
tensor([1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 0, 0, 1, 0, 0], device='cuda:0')
tensor([1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
        1, 0, 0, 0, 0, 0, 1, 0], device='cuda:0')
tensor([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 1], device='cuda:0')
tensor([1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
        1, 1, 0, 0, 0, 0, 1, 1], device='cuda:0')


In [11]:
model = AgeGenderModel()
print(next(model.parameters()).dtype)

torch.float32


In [13]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = AgeGenderModel().to(device)

age_criterion = MSELoss()
gender_criterion = CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = 0.001)

In [14]:
num_epochs = 20

train_age_losses = []
val_age_losses = []

train_gender_losses = []
val_gender_losses = []

for epoch in range(num_epochs):
    start_time = time.time()
    model.train()
    total_age_loss = 0.0
    total_gender_loss = 0.0
    for  i,(images, labels) in enumerate(train_loader):
        images = images.to(device)
        ages = labels[:, 0].to(device)
        genders = labels[:, 1].long().to(device)

        optimizer.zero_grad()

        age_preds, gender_preds = model(images)
        age_loss = age_criterion(age_preds.squeeze(), ages)
        gender_loss = gender_criterion(gender_preds.squeeze(), genders)

        loss = age_loss + gender_loss
        loss.backward()
        optimizer.step()

        total_age_loss += age_loss.item()
        total_gender_loss += gender_loss.item()

    train_age_losses.append(total_age_loss / len(train_loader))
    train_gender_losses.append(total_gender_loss / len(train_loader))

    model.eval()
    val_age_loss = 0.0
    val_gender_loss = 0.0
    with torch.no_grad():
        for i, (images, labels) in enumerate(val_loader):
            images = images.to(device)
            ages = labels[:, 0].to(device)
            genders = labels[:, 1].long().to(device)

            age_preds, gender_preds = model(images)
            age_loss = age_criterion(age_preds.squeeze(), ages)
            gender_loss = gender_criterion(gender_preds.squeeze(), genders)

            val_age_loss += age_loss.item()
            val_gender_loss += gender_loss.item()

    val_age_losses.append(val_age_loss / len(val_loader))   
    val_gender_losses.append(val_gender_loss / len(val_loader))
    end_time = time.time()
    print(f"Epoch [{epoch+1}/{num_epochs}] - "
          f"Train Age Loss: {train_age_losses[-1]:.4f}, Train Gender Loss: {train_gender_losses[-1]:.4f}, "
          f"Val Age Loss: {val_age_losses[-1]:.4f}, Val Gender Loss: {val_gender_losses[-1]:.4f}, Time: {end_time - start_time:.2f} seconds")
torch.save(model.state_dict(), 'age_gender_augmented_model.pth')


Epoch [1/20] - Train Age Loss: 186.6566, Train Gender Loss: 0.6808, Val Age Loss: 161.8841, Val Gender Loss: 0.6536, Time: 226.50 seconds
Epoch [2/20] - Train Age Loss: 109.6867, Train Gender Loss: 0.6652, Val Age Loss: 93.1699, Val Gender Loss: 0.6387, Time: 215.01 seconds
Epoch [3/20] - Train Age Loss: 83.6564, Train Gender Loss: 0.6433, Val Age Loss: 87.7298, Val Gender Loss: 0.6811, Time: 214.88 seconds
Epoch [4/20] - Train Age Loss: 65.6800, Train Gender Loss: 0.6051, Val Age Loss: 69.1029, Val Gender Loss: 0.5547, Time: 216.55 seconds
Epoch [5/20] - Train Age Loss: 52.4640, Train Gender Loss: 0.5636, Val Age Loss: 59.6928, Val Gender Loss: 0.5355, Time: 216.78 seconds
Epoch [6/20] - Train Age Loss: 45.8711, Train Gender Loss: 0.5232, Val Age Loss: 63.8364, Val Gender Loss: 0.5201, Time: 216.11 seconds
Epoch [7/20] - Train Age Loss: 36.6528, Train Gender Loss: 0.5080, Val Age Loss: 79.2903, Val Gender Loss: 0.4978, Time: 215.48 seconds
Epoch [8/20] - Train Age Loss: 33.2882, Train