In [1]:
import torch
from torch.utils.data import DataLoader, random_split
from torch.nn import MSELoss, CrossEntropyLoss
from torchvision import transforms
import torch.optim as optim
import os
import time

from data_loader import FaceDataset
from model import AgeGenderModel
torch.cuda.is_available()

True

In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


In [3]:
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

In [4]:
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])  

full_dataset = FaceDataset(root_dir='dataset', transform=transform)

In [5]:
filtered_indices = [i for i, (data, label) in enumerate(full_dataset) if data is not None]
dataset = torch.utils.data.Subset(full_dataset, filtered_indices)

train_size = int(0.8 * len(dataset))
val_size = int(0.1 * len(dataset))
test_size = len(dataset) - train_size - val_size
train_dataset, val_dataset, test_dataset = random_split(dataset, [train_size, val_size, test_size])


In [6]:
train_loader = DataLoader(train_dataset, batch_size = 32, shuffle = True, num_workers = 4)
val_loader = DataLoader(val_dataset, batch_size = 32, shuffle = False, num_workers = 4)
test_loader = DataLoader(test_dataset, batch_size = 32, shuffle = False, num_workers = 4)

In [7]:
image_files = [f for f in os.listdir('dataset') if f.endswith(".jpg")]
len(image_files)
for i in image_files:
    parts = i.split('_')
    gender = int(parts[1])
    if gender > 1:
        print(gender, i)

In [8]:
next(iter(train_loader))[1].shape
next(iter(train_loader))[1][:, 1]
z = 1
for i, (images, labels) in enumerate(train_loader) :
    images = images.to(device)
    ages = labels[:, 0].to(device)
    genders = labels[:, 1].long().to(device)
    print(genders)
    z += 1
    if z > 5: break

tensor([0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
        0, 0, 1, 0, 1, 1, 0, 1], device='cuda:0')
tensor([1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 0, 0, 1, 0, 0], device='cuda:0')
tensor([1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
        1, 0, 0, 0, 0, 0, 1, 0], device='cuda:0')
tensor([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 1], device='cuda:0')
tensor([1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
        1, 1, 0, 0, 0, 0, 1, 1], device='cuda:0')


In [9]:
model = AgeGenderModel()
print(next(model.parameters()).dtype)

torch.float32


In [10]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = AgeGenderModel().to(device)

age_criterion = MSELoss()
gender_criterion = CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = 0.001)

In [13]:
num_gender_classes = 2

num_epochs = 20
for epoch in range(num_epochs):
    start_time = time.time()
    model.train()
    running_loss = 0.0
    for i, (images, labels) in enumerate(train_loader) :
        images = images.to(device)
        ages = labels[:, 0].to(device)
        genders = labels[:, 1].long().to(device)
        #max_gender = genders.max().item()
        #if max_gender >= num_gender_classes:
        #    print(i, genders)
        #    print(f"Error in batch {i} Epoch {epoch+1}")
        #    print(f"Maximun gender value {max_gender}")
        #    break

        optimizer.zero_grad()

        age_pred, gender_pred = model(images)

        age_loss = age_criterion(age_pred.squeeze(), ages)
        gender_loss = gender_criterion(gender_pred, genders)
        total_loss = age_loss + gender_loss

        total_loss.backward()

        optimizer.step()

        running_loss += total_loss.item()
    end_time = time.time()
    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {running_loss/len(train_loader):4f}, Time: {end_time - start_time:.2f}sec")

torch.save(model.state_dict(),'models/model_removing_age_gt90.pth')
print("Training complete. Model saved.")


Epoch 1/20, Loss: 101.377048, Time: 18.64sec
Epoch 2/20, Loss: 87.842206, Time: 18.17sec
Epoch 3/20, Loss: 67.018800, Time: 18.14sec
Epoch 4/20, Loss: 53.015301, Time: 18.16sec
Epoch 5/20, Loss: 46.988747, Time: 18.13sec
Epoch 6/20, Loss: 46.591953, Time: 18.21sec
Epoch 7/20, Loss: 36.143602, Time: 18.36sec
Epoch 8/20, Loss: 30.419477, Time: 18.18sec
Epoch 9/20, Loss: 90.035054, Time: 18.15sec
Epoch 10/20, Loss: 63.302679, Time: 18.21sec
Epoch 11/20, Loss: 31.253023, Time: 18.29sec
Epoch 12/20, Loss: 18.019624, Time: 18.41sec
Epoch 13/20, Loss: 13.482615, Time: 18.24sec
Epoch 14/20, Loss: 10.798305, Time: 18.39sec
Epoch 15/20, Loss: 11.806152, Time: 18.27sec
Epoch 16/20, Loss: 11.445902, Time: 18.32sec
Epoch 17/20, Loss: 9.802235, Time: 18.22sec
Epoch 18/20, Loss: 9.986628, Time: 18.28sec
Epoch 19/20, Loss: 8.228476, Time: 18.19sec
Epoch 20/20, Loss: 7.618810, Time: 18.13sec
Training complete. Model saved.
